version: '3.9'

services:
  parking-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb-container:27017/parking-lot-management
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
# https://github.com/arunbandari/mongo-gui

volumes:
  mongo_data:
